### ISSUE TITLE
Closed API v1

### ISSUE THREAD

**Issue by jonkristian** [reidarw/MMM-TRV-WastePlan#3]
Looks like they've closed api/v1 and that there is a new api/v2 out, however this is as far as I get when trying to figure out the endpoints. `https://trv.no/wp-json/wasteplan/v2/adress/?s=Address`

Let me know if you take a look at it, if you have any luck.

**Comment by reidarw** [comment]
Yes! I'll let you know if I find the correct endpoint.

**Comment by jkaberg** [comment]
The iCal links now work, so that's a possible solution. Eg https://trv.no/calendar/486ae278-a5a8-4284-92a4-c07d484a8b95/

**Comment by reidarw** [comment]
Nice. iCal is also nice to have. I forgot to update this, but I rewrote this module after they released the API v2 two months ago.
